const players = [
    { id: 1, name: "Asahi Naruhaya", image: "images/asahi-naruhaya.jpg" },
    { id: 2, name: "Gin Gagamaru", image: "images/gin-gagamaru.jpg" },
    { id: 3, name: "Gurimu Igarashi", image: "images/gurimu-igarashi.jpg" },
    { id: 4, name: "Hyoma Chigiri", image: "images/hyoma-chigiri.jpg" },
    { id: 5, name: "Jingo Raichi", image: "images/jingo-raichi.jpg" },

    { id: 6, name: "Meguru Bachira", image: "images/meguru-bachira.jpg" },
    { id: 7, name: "Okuhito Iemon", image: "images/okuhito-iemon.jpg" },
    { id: 8, name: "Rensuke Kunigami", image: "images/rensuke-kunigami.jpg" },
    { id: 9, name: "Wataru Kuon", image: "images/wataru-kuon.jpg" },
    { id: 10, name: "Yoichi Isagi", image: "images/yoichi-isagi.jpg" },
    { id: 11, name: "Yudai Imamura", image: "images/yudai-imamura.jpg" },

    { id: 12, name: "Ryosuke Kira", image: "images/ryosuke-kira.jpg" },
    { id: 13, name: "Shoei Baro", image: "images/shoei-baro.jpg" },
    { id: 14, name: "Hibiki Okawa", image: "images/hibiki-okawa.jpg" },
    { id: 15, name: "Ikki Niko", image: "images/ikki-niko.jpg" },
    { id: 16, name: "Junichi Wanima", image: "images/junichi-wanima.jpg" },
    { id: 17, name: "Keisuke Wanima", image: "images/keisuke-wanima.jpg" },
    { id: 18, name: "Reo Mikage", image: "images/reo-mikage.jpg" },
    { id: 19, name: "Seishiro Nagi", image: "images/seishiro-nagi.jpg" },
    { id: 20, name: "Zantetsu Tsurugi", image: "images/zantetsu-tsurugi.jpg" },

    { id: 21, name: "Aoshi Tokimitsu", image: "images/aoshi-tokimitsu.jpg" },
    { id: 22, name: "Eita Otoya", image: "images/eita-otoya.jpg" },
    { id: 23, name: "Jin Kiyora", image: "images/jin-kiyora.jpg" },
    { id: 24, name: "Jyubei Aryu", image: "images/jyubei-aryu.jpg" },
    { id: 25, name: "Kenyu Yukimiya", image: "images/kenyu-yukimiya.jpg" },
    { id: 26, name: "Ranze Kurona", image: "images/ranze-kurona.jpg" },
    { id: 27, name: "Nijiro Nanase", image: "images/nijiro-nanase.jpg" },
    { id: 28, name: "Rin Itoshi", image: "images/rin-itoshi.jpg" },
    { id: 29, name: "Ryusei Shido", image: "images/ryusei-shido.jpg" },
    { id: 30, name: "Tabito Karasu", image: "images/tabito-karasu.jpg" },
    { id: 31, name: "Yo Hiori", image: "images/yo-hiori.jpg" },

    { id: 32, name: "Adam Blake", image: "images/adam-blake.jpg" },
    { id: 33, name: "Dada Silva", image: "images/dada-silva.jpg" },
    { id: 34, name: "Julien Loki", image: "images/julien-loki.jpg" },
    { id: 35, name: "Leonardo Luna", image: "images/leonardo-luna.jpg" },
    { id: 36, name: "Pablo Cavasoz", image: "images/pablo-cavasoz.jpg" },

    { id: 37, name: "Gen Fukaku", image: "images/gen-fukaku.jpg" },
    { id: 38, name: "Oliver Aiku", image: "images/oliver-aiku.jpg" },
    { id: 39, name: "Kazuma Nio", image: "images/kazuma-nio.jpg" },
    { id: 40, name: "Miroku Darai", image: "images/miroku-darai.jpg" },
    { id: 41, name: "Teppei Neru", image: "images/teppei-neru.jpg" },
    { id: 42, name: "Itsuki Wakatsuki", image: "images/itsuki-wakatsuki.jpg" },
    { id: 43, name: "Haru Hayate", image: "images/haru-hayate.jpg" },
    { id: 44, name: "Sae Itoshi", image: "images/sae-itoshi.jpg" },

    { id: 45, name: "Noel Noa", image: "images/noel-noa.jpg" },
    { id: 46, name: "Benedict Grim", image: "images/benedict-grim.jpg" },
    { id: 47, name: "Michael Kaiser", image: "images/michael-kaiser.jpg" },
    { id: 48, name: "Lavinho", image: "images/lavinho.jpg" },
    { id: 49, name: "Chris Prince", image: "images/chris-prince.jpg" },
    { id: 50, name: "Rooke", image: "images/rooke.jpg" },
    { id: 51, name: "Marc Snuffy", image: "images/marc-snuffy.jpg" },
    { id: 52, name: "Don Lorenzo", image: "images/don-lorenzo.jpg" },
    { id: 53, name: "Charles Chevalier", image: "images/charles-chevalier.jpg" },
    { id: 54, name: "Renoir", image: "images/renoir.jpg" },

    { id: 55, name: "Haneru Shindo", image: "images/haneru-shindo.jpg" },
    { id: 56, name: "Innocent Onazi", image: "images/innocent-onazi.jpg" },
    { id: 57, name: "Godwin Kuso", image: "images/godwin-kuso.jpg" },
    { id: 58, name: "Vivien Hugo", image: "images/vivien-hugo.jpg" },
    { id: 59, name: "Bunny Iglesias", image: "images/bunny-iglesias.jpg" },
    { id: 60, name: "Achanpong", image: "images/achanpong.jpg" },
    { id: 61, name: "Lockhart", image: "images/lockhart.jpg" },
    { id: 62, name: "Teddy Knight", image: "images/teddy-knight.jpg" },
    { id: 63, name: "Childs", image: "images/childs.jpg" },

    { id: 64, name: "Agi", image: "images/agi.jpg" },
    { id: 65, name: "Alexis Ness", image: "images/alexis-ness.jpg" },
    { id: 66, name: "Kento Cho", image: "images/kento-cho.jpg" },
    { id: 67, name: "Teru Kitsunezato", image: "images/teru-kitsunezato.jpg" },
    { id: 68, name: "Shuto Sendo", image: "images/shuto-sendo.jpg" }
];
